// AUTO-GENERATED by `npm run db:pull`. Do not edit by hand.
// Source of truth is the live database. To change the schema:
//   1. Apply the migration in the Laravel project (database/migrations).
//   2. Run `php artisan migrate` against the shared DB.
//   3. Run `npm run db:pull` here to regenerate this file.

import { AnyMySqlColumn, bigint, boolean, float, foreignKey, index, int, json, mysqlSchema, mysqlTable, primaryKey, text, timestamp, tinyint, unique, varchar } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const competition = mysqlTable("Competition", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonID: bigint("seasonID", { mode: "number" }).notNull().references(() => season.id),
	ownerUserID: bigint("ownerUserID", { mode: "number" }).notNull().references(() => user.id),
},
(table) => [
	index("ownerUserID").on(table.ownerUserID),
	index("seasonID").on(table.seasonID),
	primaryKey({ columns: [table.id], name: "Competition_id"}),
]);

export const competitionRider = mysqlTable("CompetitionRider", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonRiderID: bigint("seasonRiderID", { mode: "number" }).notNull().references(() => seasonRider.id),
	competitionTeamID: bigint("competitionTeamID", { mode: "number" }).notNull().references(() => competitionTeam.id),
	fitnessLevel: float("fitnessLevel").notNull(),
	shapeLevel: float("shapeLevel").notNull(),
	moraleLevel: float("moraleLevel").notNull(),
	sprintLevel: float("sprintLevel").notNull(),
	punchLevel: float("punchLevel").notNull(),
	soloLevel: float("soloLevel").notNull(),
	climbingLevel: float("climbingLevel").notNull(),
	enduranceLevel: float("enduranceLevel").notNull(),
	recoveryLevel: float("recoveryLevel").notNull(),
	tacticalLevel: float("tacticalLevel").notNull(),
	courageLevel: float("courageLevel").notNull(),
	resilienceLevel: float("resilienceLevel").notNull(),
},
(table) => [
	index("competitionTeamID").on(table.competitionTeamID),
	index("seasonRiderID").on(table.seasonRiderID),
	primaryKey({ columns: [table.id], name: "CompetitionRider_id"}),
]);

export const competitionTeam = mysqlTable("CompetitionTeam", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	userID: bigint("userID", { mode: "number" }).notNull().references(() => user.id),
	competitionID: bigint("competitionID", { mode: "number" }).notNull().references(() => competition.id),
	seasonTeamID: bigint("seasonTeamID", { mode: "number" }).notNull().references(() => seasonTeam.id),
	isRobot: boolean("isRobot"),
	moraleLevel: float("moraleLevel").notNull(),
	cooperationLevel: float("cooperationLevel").notNull(),
	leadOutLevel: float("leadOutLevel").notNull(),
	climbBikeLevel: float("climbBikeLevel").notNull(),
	timeTrialBikeLevel: float("timeTrialBikeLevel").notNull(),
	tireLevel: float("tireLevel").notNull(),
	tireType: varchar("tireType", { length: 500 }).notNull(),
	nutritionLevel: float("nutritionLevel").notNull(),
	helmetLevel: float("helmetLevel").notNull(),
	clothingLevel: float("clothingLevel").notNull(),
},
(table) => [
	index("competitionID").on(table.competitionID),
	index("seasonTeamID").on(table.seasonTeamID),
	index("userID").on(table.userID),
	primaryKey({ columns: [table.id], name: "CompetitionTeam_id"}),
]);

export const course = mysqlTable("Course", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }).notNull(),
	endSequence: bigint("endSequence", { mode: "number" }),
	type: varchar("type", { length: 255 }),
},
(table) => [
	primaryKey({ columns: [table.id], name: "Course_id"}),
]);

export const coursePoint = mysqlTable("CoursePoint", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	sequence: bigint("sequence", { mode: "number" }).notNull(),
	courseID: bigint("courseID", { mode: "number" }).notNull().references(() => course.id),
	courseSubSegmentID: bigint("courseSubSegmentID", { mode: "number" }).notNull().references(() => courseSubSegment.id),
	lat: float("lat").notNull(),
	long: float("long").notNull(),
	elevation: float("elevation").notNull(),
	distanceFromStart: float("distanceFromStart").notNull(),
},
(table) => [
	index("courseID").on(table.courseID),
	index("courseSubSegmentID").on(table.courseSubSegmentID),
	primaryKey({ columns: [table.id], name: "CoursePoint_id"}),
	unique("index_2").on(table.sequence, table.courseID),
]);

export const courseSegment = mysqlTable("CourseSegment", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	type: varchar("type", { length: 255 }).notNull(),
	courseID: bigint("courseID", { mode: "number" }).notNull().references(() => course.id),
	name: varchar("name", { length: 255 }).notNull(),
	description: text("description"),
	category: varchar("category", { length: 255 }),
},
(table) => [
	index("courseID").on(table.courseID),
	primaryKey({ columns: [table.id], name: "CourseSegment_id"}),
]);

export const courseSubSegment = mysqlTable("CourseSubSegment", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }),
	description: text("description"),
	courseID: bigint("courseID", { mode: "number" }).notNull().references(() => course.id),
	courseSegmentID: bigint("courseSegmentID", { mode: "number" }).notNull().references(() => courseSegment.id),
	distance: float("distance").notNull(),
	elevationDiff: float("elevationDiff").notNull(),
	startSequence: bigint("startSequence", { mode: "number" }),
	endSequence: bigint("endSequence", { mode: "number" }),
	isKeySegment: boolean("isKeySegment"),
	surface: varchar("surface", { length: 255 }),
	averageElevation: float("averageElevation").notNull(),
	breakAwayProbability: int("breakAwayProbability"),
	averageDirection: int("averageDirection"),
},
(table) => [
	index("courseID").on(table.courseID),
	index("courseSegmentID").on(table.courseSegmentID),
	primaryKey({ columns: [table.id], name: "CourseSubSegment_id"}),
]);

export const race = mysqlTable("Race", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonRaceID: bigint("seasonRaceID", { mode: "number" }).notNull().references(() => seasonRace.id),
	competitionID: bigint("competitionID", { mode: "number" }).notNull().references(() => competition.id),
	status: varchar("status", { length: 255 }).notNull(),
	startTimestamp: timestamp("startTimestamp", { mode: 'string' }).notNull(),
	seed: varchar("seed", { length: 255 }).notNull(),
	weatherData: json("weatherData"),
},
(table) => [
	index("competitionID").on(table.competitionID),
	index("seasonRaceID").on(table.seasonRaceID),
	primaryKey({ columns: [table.id], name: "Race_id"}),
]);

export const raceEvent = mysqlTable("RaceEvent", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	raceTickID: bigint("raceTickID", { mode: "number" }).notNull().references(() => raceTick.id),
	timeElapsed: bigint("timeElapsed", { mode: "number" }),
	type: varchar("type", { length: 255 }),
	data: json("data"),
},
(table) => [
	index("raceTickID").on(table.raceTickID),
	primaryKey({ columns: [table.id], name: "RaceEvent_id"}),
]);

export const seasonRaceGroupSelectedRider = mysqlTable("SeasonRaceGroupSelectedRider", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonRaceGroupID: bigint("seasonRaceGroupID", { mode: "number" }).notNull().references(() => seasonRaceGroup.id),
	competitionID: bigint("competitionID", { mode: "number" }).notNull().references(() => competition.id),
	competitionRiderID: bigint("competitionRiderID", { mode: "number" }).notNull().references(() => competitionRider.id),
	role: varchar("role", { length: 500 }),
},
(table) => [
	index("competitionID").on(table.competitionID),
	index("competitionRiderID").on(table.competitionRiderID),
	index("seasonRaceGroupID").on(table.seasonRaceGroupID),
	primaryKey({ columns: [table.id], name: "SeasonRaceGroupSelectedRider_id"}),
]);

export const competitionTeamRaceGroup = mysqlTable("CompetitionTeamRaceGroup", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	competitionTeamID: bigint("competitionTeamID", { mode: "number" }).references(() => competitionTeam.id),
	seasonRaceGroupID: bigint("seasonRaceGroupID", { mode: "number" }).references(() => seasonRaceGroup.id),
	objective: varchar("objective", { length: 500 }),
	riderRoleFormation: json("riderRoleFormation"),
	riderRoleObjectives: json("riderRoleObjectives"),
},
(table) => [
	index("competitionTeamID").on(table.competitionTeamID),
	index("seasonRaceGroupID").on(table.seasonRaceGroupID),
	primaryKey({ columns: [table.id], name: "CompetitionTeamRaceGroup_id"}),
]);

export const raceInstruction = mysqlTable("RaceInstruction", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	competitionTeamID: bigint("competitionTeamID", { mode: "number" }).notNull().references(() => competitionTeam.id),
	seasonRaceID: bigint("seasonRaceID", { mode: "number" }).notNull().references(() => seasonRace.id),
	courseSubSegmentID: bigint("courseSubSegmentID", { mode: "number" }).notNull().references(() => courseSubSegment.id),
	type: varchar("type", { length: 500 }).notNull(),
	instruction: varchar("instruction", { length: 500 }),
},
(table) => [
	index("competitionTeamID").on(table.competitionTeamID),
	index("courseSubSegmentID").on(table.courseSubSegmentID),
	index("seasonRaceID").on(table.seasonRaceID),
	primaryKey({ columns: [table.id], name: "RaceInstruction_id"}),
]);

export const raceInstructionRider = mysqlTable("RaceInstructionRider", {
	raceGroupSelectedRiderID: bigint("raceGroupSelectedRiderID", { mode: "number" }).notNull().references(() => seasonRaceGroupSelectedRider.id),
	raceInstructionID: bigint("raceInstructionID", { mode: "number" }).notNull().references(() => raceInstruction.id),
	extraInstruction: varchar("extraInstruction", { length: 500 }),
},
(table) => [
	index("raceInstructionID").on(table.raceInstructionID),
	primaryKey({ columns: [table.raceGroupSelectedRiderID, table.raceInstructionID], name: "RaceInstructionRider_raceGroupSelectedRiderID_raceInstructionID"}),
]);

export const raceTick = mysqlTable("RaceTick", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	raceID: bigint("raceID", { mode: "number" }).notNull().references(() => race.id),
	raceTimeElapsed: bigint("raceTimeElapsed", { mode: "number" }).notNull(),
	lastSaveTimestamp: bigint("lastSaveTimestamp", { mode: "number" }),
	saveInterval: bigint("saveInterval", { mode: "number" }),
},
(table) => [
	index("raceID").on(table.raceID),
	primaryKey({ columns: [table.id], name: "RaceTick_id"}),
]);

export const raceTickRider = mysqlTable("RaceTickRider", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	raceTickID: bigint("raceTickID", { mode: "number" }).notNull().references(() => raceTick.id),
	competitionRiderID: bigint("competitionRiderID", { mode: "number" }).notNull().references(() => competitionRider.id),
	raceTickRiderGroupID: bigint("raceTickRiderGroupID", { mode: "number" }).notNull().references(() => raceTickRiderGroup.id),
	groupRole: varchar("groupRole", { length: 255 }).notNull(),
	groupPosition: int("groupPosition").notNull(),
	aerobicEnergyLevel: float("aerobicEnergyLevel").notNull(),
	anaerobicEnergyLevel: float("anaerobicEnergyLevel").notNull(),
	anaerobicEnergyLowest: float("anaerobicEnergyLowest").notNull(),
	morale: float("morale").notNull(),
},
(table) => [
	index("competitionRiderID").on(table.competitionRiderID),
	index("raceTickID").on(table.raceTickID),
	index("raceTickRiderGroupID").on(table.raceTickRiderGroupID),
	primaryKey({ columns: [table.id], name: "RaceTickRider_id"}),
]);

export const raceTickRiderGroup = mysqlTable("RaceTickRiderGroup", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	raceTickID: bigint("raceTickID", { mode: "number" }).notNull().references(() => raceTick.id),
	distanceElapsed: float("distanceElapsed"),
	finishTimestamp: bigint("finishTimestamp", { mode: "number" }),
	status: varchar("status", { length: 255 }),
	activityState: varchar("activityState", { length: 255 }),
	currentSpeed: float("currentSpeed"),
	checkPointCrossings: json("checkPointCrossings"),
	lastEventCalculationTimestamp: bigint("lastEventCalculationTimestamp", { mode: "number" }),
	type: varchar("type", { length: 500 }),
	stoppedUntil: bigint("stoppedUntil", { mode: "number" }),
	incidentType: varchar("incidentType", { length: 500 }),
},
(table) => [
	index("raceTickID").on(table.raceTickID),
	primaryKey({ columns: [table.id], name: "RaceTickRiderGroup_id"}),
]);

export const rider = mysqlTable("Rider", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "Rider_id"}),
]);

export const season = mysqlTable("Season", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }).notNull(),
	year: int("year").notNull(),
	type: varchar("type", { length: 255 }),
},
(table) => [
	primaryKey({ columns: [table.id], name: "Season_id"}),
]);

export const seasonRace = mysqlTable("SeasonRace", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonRaceGroupID: bigint("seasonRaceGroupID", { mode: "number" }).notNull().references(() => seasonRaceGroup.id),
	courseID: bigint("courseID", { mode: "number" }).notNull().references(() => course.id),
	day: int("day").notNull(),
},
(table) => [
	index("courseID").on(table.courseID),
	index("seasonRaceGroupID").on(table.seasonRaceGroupID),
	primaryKey({ columns: [table.id], name: "SeasonRace_id"}),
]);

export const seasonRaceGroup = mysqlTable("SeasonRaceGroup", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }).notNull(),
	type: varchar("type", { length: 255 }).notNull(),
	seasonID: bigint("seasonID", { mode: "number" }).notNull().references(() => season.id),
	dayStart: int("dayStart").notNull(),
	dayEnd: int("dayEnd").notNull(),
},
(table) => [
	index("seasonID").on(table.seasonID),
	primaryKey({ columns: [table.id], name: "SeasonRaceGroup_id"}),
]);

export const seasonRider = mysqlTable("SeasonRider", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	riderID: bigint("riderID", { mode: "number" }).notNull().references(() => rider.id),
	seasonTeamID: bigint("seasonTeamID", { mode: "number" }).notNull().references(() => seasonTeam.id),
},
(table) => [
	index("riderID").on(table.riderID),
	index("seasonTeamID").on(table.seasonTeamID),
	primaryKey({ columns: [table.id], name: "SeasonRider_id"}),
]);

export const seasonTeam = mysqlTable("SeasonTeam", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	seasonID: bigint("seasonID", { mode: "number" }).notNull().references(() => season.id),
	teamID: bigint("teamID", { mode: "number" }).notNull().references(() => team.id),
	startBudget: float("startBudget").notNull(),
},
(table) => [
	index("seasonID").on(table.seasonID),
	index("teamID").on(table.teamID),
	primaryKey({ columns: [table.id], name: "SeasonTeam_id"}),
]);

export const team = mysqlTable("Team", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
	name: varchar("name", { length: 255 }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "Team_id"}),
]);

export const user = mysqlTable("User", {
	id: bigint("id", { mode: "number" }).autoincrement().notNull(),
},
(table) => [
	primaryKey({ columns: [table.id], name: "User_id"}),
]);
