import React, { useMemo } from 'react';
import { Download } from 'lucide-react';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogInternalContent,
    DialogTitle,
} from '@/components/dialog/dialog';
import { Button } from '@/components/button/button';
import { CodeSnippet } from '@/components/code-snippet/code-snippet';
import type { Diagram } from '@/lib/domain/diagram';
import { generateDrizzleSchema } from '@/lib/drizzle/drizzle-export';

export interface RevisionDrizzleDialogProps {
    open: boolean;
    onClose: () => void;
    // The revision snapshot to generate a Drizzle schema.ts from.
    diagram: Diagram | null;
    revisionName: string;
}

const sanitizeFileName = (name: string) =>
    name.replace(/[^a-zA-Z0-9-_]+/g, '_').replace(/^_+|_+$/g, '') || 'schema';

export const RevisionDrizzleDialog: React.FC<RevisionDrizzleDialogProps> = ({
    open,
    onClose,
    diagram,
    revisionName,
}) => {
    const code = useMemo(() => {
        if (!diagram) return '';
        const { code } = generateDrizzleSchema(diagram, {
            headerComment: `// Generated by ChartDB from revision "${revisionName}". Do not edit by hand.`,
        });
        return code;
    }, [diagram, revisionName]);

    const handleDownload = () => {
        const blob = new Blob([code], { type: 'text/typescript' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.setAttribute(
            'download',
            `${sanitizeFileName(revisionName)}.schema.ts`
        );
        a.setAttribute('href', url);
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <Dialog
            open={open}
            onOpenChange={(o) => {
                if (!o) onClose();
            }}
        >
            <DialogContent
                className="flex max-h-screen flex-col overflow-y-auto xl:min-w-[75vw]"
                showClose
            >
                <DialogHeader>
                    <DialogTitle>Drizzle schema.ts</DialogTitle>
                    <DialogDescription>
                        Drizzle ORM schema generated from revision &quot;
                        {revisionName}&quot;.
                    </DialogDescription>
                </DialogHeader>
                <DialogInternalContent>
                    <div className="flex flex-1 items-center justify-center">
                        <CodeSnippet
                            className="h-96 w-full"
                            code={code}
                            language="typescript"
                        />
                    </div>
                </DialogInternalContent>
                <DialogFooter className="flex !justify-between gap-2">
                    <Button
                        type="button"
                        variant="outline"
                        className="gap-1.5"
                        onClick={handleDownload}
                        disabled={!code}
                    >
                        <Download className="size-4" />
                        Download schema.ts
                    </Button>
                    <DialogClose asChild>
                        <Button type="button" variant="secondary">
                            Close
                        </Button>
                    </DialogClose>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};
