import type { Diagram } from '@/lib/domain';
import { DatabaseType } from '@/lib/domain';
import { describe, it, expect } from 'vitest';
import { generateDrizzleSchema } from '../drizzle-export';

const t = (id: string, name: string) => ({ id, name });

// A small MySQL diagram: season <- competition (FK), with a PK index and
// a secondary index, mirroring the user's drizzle-kit pull style.
const mysqlDiagram: Diagram = {
    id: 'd1',
    name: 'Game',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    databaseType: DatabaseType.MYSQL,
    tables: [
        {
            id: 'season',
            name: 'Season',
            x: 0,
            y: 0,
            color: '#fff',
            isView: false,
            createdAt: 0,
            fields: [
                {
                    id: 'season_id',
                    name: 'id',
                    type: t('bigint', 'bigint'),
                    primaryKey: true,
                    unique: false,
                    nullable: false,
                    increment: true,
                    createdAt: 0,
                },
                {
                    id: 'season_name',
                    name: 'name',
                    type: t('varchar', 'varchar'),
                    primaryKey: false,
                    unique: false,
                    nullable: false,
                    characterMaximumLength: '255',
                    createdAt: 0,
                },
                {
                    id: 'season_year',
                    name: 'year',
                    type: t('int', 'int'),
                    primaryKey: false,
                    unique: false,
                    nullable: false,
                    createdAt: 0,
                },
            ],
            indexes: [
                {
                    id: 'season_pk',
                    name: 'Season_id',
                    unique: true,
                    isPrimaryKey: true,
                    fieldIds: ['season_id'],
                    createdAt: 0,
                },
            ],
        },
        {
            id: 'competition',
            name: 'Competition',
            x: 0,
            y: 0,
            color: '#fff',
            isView: false,
            createdAt: 0,
            fields: [
                {
                    id: 'comp_id',
                    name: 'id',
                    type: t('bigint', 'bigint'),
                    primaryKey: true,
                    unique: false,
                    nullable: false,
                    increment: true,
                    createdAt: 0,
                },
                {
                    id: 'comp_seasonID',
                    name: 'seasonID',
                    type: t('bigint', 'bigint'),
                    primaryKey: false,
                    unique: false,
                    nullable: false,
                    createdAt: 0,
                },
                {
                    id: 'comp_fitness',
                    name: 'fitnessLevel',
                    type: t('float', 'float'),
                    primaryKey: false,
                    unique: false,
                    nullable: false,
                    createdAt: 0,
                },
                {
                    id: 'comp_note',
                    name: 'note',
                    type: t('text', 'text'),
                    primaryKey: false,
                    unique: false,
                    nullable: true,
                    createdAt: 0,
                },
            ],
            indexes: [
                {
                    id: 'comp_pk',
                    name: 'Competition_id',
                    unique: true,
                    isPrimaryKey: true,
                    fieldIds: ['comp_id'],
                    createdAt: 0,
                },
                {
                    id: 'comp_idx',
                    name: 'seasonID',
                    unique: false,
                    isPrimaryKey: false,
                    fieldIds: ['comp_seasonID'],
                    createdAt: 0,
                },
            ],
        },
    ],
    relationships: [
        {
            id: 'rel1',
            name: 'fk_comp_season',
            sourceTableId: 'season',
            sourceFieldId: 'season_id',
            targetTableId: 'competition',
            targetFieldId: 'comp_seasonID',
            sourceCardinality: 'one',
            targetCardinality: 'many',
            createdAt: 0,
        },
    ],
    dependencies: [],
    areas: [],
    customTypes: [],
};

describe('generateDrizzleSchema (mysql)', () => {
    const { code, dialect } = generateDrizzleSchema(mysqlDiagram, {
        headerComment: '// Generated by ChartDB',
    });

    it('uses the mysql-core dialect', () => {
        expect(dialect).toBe('mysql');
        expect(code).toContain('from "drizzle-orm/mysql-core"');
    });

    it('emits the header comment', () => {
        expect(code.startsWith('// Generated by ChartDB')).toBe(true);
    });

    it('emits camelCase exports with original table name', () => {
        expect(code).toContain('export const season = mysqlTable("Season", {');
        expect(code).toContain(
            'export const competition = mysqlTable("Competition", {'
        );
    });

    it('emits bigint autoincrement primary key columns', () => {
        expect(code).toContain(
            'id: bigint("id", { mode: "number" }).autoincrement().notNull(),'
        );
    });

    it('emits varchar with length and notNull', () => {
        expect(code).toContain(
            'name: varchar("name", { length: 255 }).notNull(),'
        );
    });

    it('emits nullable column without notNull', () => {
        expect(code).toContain('note: text("note"),');
        expect(code).not.toContain('note: text("note").notNull()');
    });

    it('emits inline references() for the FK column', () => {
        // JS key is camelCased (seasonId) but the column string keeps the
        // original name ("seasonID"), matching drizzle-kit pull behavior.
        expect(code).toContain(
            'seasonId: bigint("seasonID", { mode: "number" }).notNull().references(() => season.id),'
        );
    });

    it('emits index() and primaryKey() in the table callback', () => {
        expect(code).toContain('index("seasonID").on(table.seasonId),');
        expect(code).toContain(
            'primaryKey({ columns: [table.id], name: "Competition_id"}),'
        );
    });

    it('only imports the builders it uses', () => {
        const importLine = code
            .split('\n')
            .find((l) => l.includes('drizzle-orm/mysql-core'))!;
        // The table constructor must be imported too.
        expect(importLine).toContain('mysqlTable');
        expect(importLine).toContain('bigint');
        expect(importLine).toContain('varchar');
        expect(importLine).toContain('float');
        expect(importLine).toContain('text');
        expect(importLine).toContain('index');
        expect(importLine).toContain('primaryKey');
        // Not used -> must be absent.
        expect(importLine).not.toContain('json');
        expect(importLine).not.toContain('boolean');
    });

    it('imports every builder identifier it references (no missing imports)', () => {
        const importLine = code
            .split('\n')
            .find((l) => l.includes('drizzle-orm/mysql-core'))!;
        const imported = new Set(
            importLine
                .replace(/.*\{([^}]*)\}.*/, '$1')
                .split(',')
                .map((s) => s.trim())
                .filter(Boolean)
        );
        // Chained methods are not imports; everything else called as `name(` is.
        const methods = new Set([
            'references',
            'on',
            'notNull',
            'autoincrement',
            'unique',
            'default',
            'primaryKey',
        ]);
        const missing = new Set<string>();
        for (const m of code.matchAll(/(?::|\t)\s*([a-zA-Z]+)\(/g)) {
            const id = m[1];
            if (id === 'sql') continue; // imported separately from drizzle-orm
            if (!methods.has(id) && !imported.has(id)) missing.add(id);
        }
        expect([...missing]).toEqual([]);
    });
});

describe('generateDrizzleSchema (postgres & sqlite dialects)', () => {
    it('maps postgres types to pg-core builders', () => {
        const pg: Diagram = {
            ...mysqlDiagram,
            databaseType: DatabaseType.POSTGRESQL,
        };
        const { code, dialect } = generateDrizzleSchema(pg);
        expect(dialect).toBe('pg');
        expect(code).toContain('from "drizzle-orm/pg-core"');
        expect(code).toContain('pgTable("Season"');
    });

    it('maps to sqlite-core builders', () => {
        const sqlite: Diagram = {
            ...mysqlDiagram,
            databaseType: DatabaseType.SQLITE,
        };
        const { code, dialect } = generateDrizzleSchema(sqlite);
        expect(dialect).toBe('sqlite');
        expect(code).toContain('from "drizzle-orm/sqlite-core"');
        expect(code).toContain('sqliteTable("Season"');
    });
});
